### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by jonassteinberg1** [mikybars/hadolint-wrapper#1]
```
Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
CentOS Linux release 7.8.2003 (Core)
Linux 3.10.0-1127.8.2.el7.x86_64
virtualenv 15.1.0
pip 20

# pip list
click      7.1.2
hadolintw  1.2.0
pip        20.1.1
setuptools 28.8.0
wheel      0.29.0

Traceback (most recent call last):
  File "/home/repo/venv/bin/hadolintw", line 11, in <module>
    sys.exit(main())
  File "/home/repo/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/repo/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/repo/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/repo/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/repo/venv/lib/python3.6/site-packages/hadolintw/main.py", line 73, in main
    process = subprocess.run(cmd, input=input_bytes, capture_output=True)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by mikybars** [comment]
Oops... it seems that the parameter `capture_output` was introduced in Python 3.7 which is the version that I have installed on my system.

Please check out the latest version of the code and let me know if it works for you.
